/**
 * Severity of a notification. Drives icon, color, and assertive vs
 * polite ARIA live-region semantics.
 */
export type NotificationType = 'success' | 'error' | 'warning' | 'info' | 'danger';

/**
 * Functional class of a notification. Each category is a separate
 * preference switch (see `NotificationPreferences`) so users can mute
 * a class without losing the others — e.g. silence rate-change updates
 * while keeping transaction confirmations.
 */
export type NotificationCategory =
  | 'transaction'
  | 'credit_line'
  | 'risk_score'
  | 'rate_change'
  | 'system';

/**
 * Persistent inbox entry. Stored in `localStorage` capped at 100 by
 * `NotificationContext` so the inbox does not grow without bound.
 */
export interface Notification {
  /** Stable id, generated by the dispatcher in NotificationContext. */
  id: string;
  type: NotificationType;
  category: NotificationCategory;
  /** Short, headline-style label. */
  title: string;
  /** One-sentence body. */
  message: string;
  /** ISO 8601 timestamp of when the notification was emitted. */
  timestamp: string;
  /** Read receipt; flipped by `markAsRead` / `markAllAsRead`. */
  read: boolean;
  /** Optional inline action — e.g. "View transaction". */
  action?: { label: string; onClick: () => void };
}

/**
 * A transient toast notification. Unlike a regular Notification, a Toast
 * is not tracked in the read/unread inbox — it lives only for the
 * duration of its display.
 */
export interface Toast extends Omit<Notification, 'read'> {
  duration?: number; // ms, default 5500
  persistent?: boolean;
}

/**
 * Page-level banner alert. Unlike toasts, banners persist until the
 * user dismisses them or the underlying condition clears.
 */
export interface BannerAlert {
  id: string;
  type: NotificationType;
  message: string;
  /** When true, the close button is rendered. Defaults to false for blocking errors. */
  dismissible?: boolean;
  /** Optional inline action — e.g. "Retry". */
  action?: { label: string; onClick: () => void };
}

/**
 * Per-category mute switches. `true` means notifications of that
 * category are delivered; `false` suppresses them silently — the
 * `addToast` dispatcher returns the empty string when a category is
 * muted, so callers can no-op without special-casing.
 */
export interface NotificationPreferences {
  transaction: boolean;
  credit_line: boolean;
  risk_score: boolean;
  rate_change: boolean;
  system: boolean;
}
